# Config
title: Spare parts
description: 'Spare parts of my mind, talking about things I do (or fail).'
tagline: 'di Roberto Valentini'
paginate: 5
paginate_path: '/page/:num'
baseurl: '/'
url: https://valantin.github.io
permalink: '/:year/:month/:title/'
excerpt_separator: ''
license:
  link: 'https://creativecommons.org/licenses/by-nc/3.0/'
  label: 'CC BY-NC'
author:
  name: Roberto Valentini
  url: https://valantin.github.io
  email: valantin89@gmail.com
twitter_username: valantin89
github_username:  Valantin

# Build settings
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-mentions
  - jekyll-paginate
  - jekill-seo-tag

defaults:
 -
   scope:
     path: "posts"
   values:
     layout: "post"
     author: "Roberto Valentini"